@echo off
echo Starting Humor Backend Server...
echo.
echo Checking if MongoDB connection is available...
node -e "console.log('Environment check:'); console.log('MONGODB_URI:', process.env.MONGODB_URI ? 'Set' : 'Not set'); console.log('JWT_SECRET:', process.env.JWT_SECRET ? 'Set' : 'Not set'); console.log('PORT:', process.env.PORT || '3001');" 
echo.
echo Starting server on port 3001...
npm start